#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width 0 

vmware-user-suid-wrapper &

feh --bg-fill /usr/share/wallpapers/custom/wallpaper.jpg &  # Set wallpaper

/usr/bin/picom &
wmname LG3D & # Fix for Java aplications not rendering properly
/usr/libexec/polkit-mate-authentication-agent-1 & # Polkit to manage apps with password requirements

~/./.config/polybar/launch.sh & # Launch Polybar
